services:
  db:
    image: postgres:latest
    container_name: teacher_booking_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "6432:6432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teacher_booking_app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8081:8081"
    volumes:
      - .:/src/app
    command: air -c .air.toml

volumes:
  postgres_data: